# Find Qt 6.8+ via CMAKE_PREFIX_PATH / QTDIR.

function(mps_find_qt)
  if(DEFINED ENV{QTDIR} AND NOT CMAKE_PREFIX_PATH)
    list(PREPEND CMAKE_PREFIX_PATH "$ENV{QTDIR}")
    set(CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH}" PARENT_SCOPE)
  endif()

  find_package(Qt6 6.8 REQUIRED COMPONENTS Core Gui Widgets Network)

  set(CMAKE_AUTOMOC ON PARENT_SCOPE)
  set(CMAKE_AUTORCC ON PARENT_SCOPE)
  set(CMAKE_AUTOUIC ON PARENT_SCOPE)

  set(MPS_QT_VERSION "${Qt6_VERSION}" PARENT_SCOPE)
  message(STATUS "Found Qt ${Qt6_VERSION}")
endfunction()
